# Generated by Django 2.0.3 on 2018-10-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0004_profilepic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilepic',
            name='user_type',
            field=models.CharField(default='Viewers', max_length=20),
        ),
    ]
