# Generated by Django 2.0.3 on 2018-10-22 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0005_profilepic_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepic',
            name='user_type',
            field=models.CharField(default='Temp_User', max_length=20),
        ),
    ]
