# Generated by Django 2.0.3 on 2018-10-12 13:33

import Gist.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gist', '0009_auto_20180928_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='gistpost',
            name='publish',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gistpost',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to=Gist.models.user_directory_path),
        ),
    ]
