# Generated by Django 2.0.3 on 2018-10-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mysteries', '0004_auto_20181010_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
