# Generated by Django 2.0.3 on 2018-10-10 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mysteries', '0006_auto_20181010_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
