# Generated by Django 2.0.3 on 2018-10-10 14:12

import Mysteries.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mysteries', '0007_auto_20181010_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='quote_picture',
            field=models.ImageField(blank=True, upload_to=Mysteries.models.user_directory_path),
        ),
    ]
