# Generated by Django 2.0.3 on 2018-11-11 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mysteries', '0008_auto_20181010_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='author',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='quote',
            name='category',
            field=models.CharField(choices=[('quote', 'QUOTE'), ('poem', 'POEM'), ('letters', 'LETTERS'), ('inspirational', 'INSPIRATIONAL')], default='love', max_length=20),
        ),
    ]
