# Generated by Django 2.0.3 on 2018-11-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mysteries', '0010_auto_20181114_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='category',
            field=models.CharField(choices=[('quote', 'QUOTE'), ('poem', 'POEM'), ('letters', 'LETTERS'), ('soul awakening', 'SOUL AWAKENING')], default='love', max_length=20),
        ),
    ]
