# Generated by Django 2.0.3 on 2018-10-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0010_auto_20180921_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsposts',
            name='publish',
            field=models.BooleanField(default=True),
        ),
    ]
