# Generated by Django 2.0.3 on 2018-10-10 17:29

import News.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0012_auto_20181010_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsposts',
            name='cover_picture',
            field=models.ImageField(blank=True, upload_to=News.models.user_directory_path),
        ),
    ]
