# Generated by Django 2.0.3 on 2018-11-09 13:22

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0013_auto_20181010_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsposts',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, max_length=300),
        ),
    ]
