# Generated by Django 2.0.3 on 2018-11-11 13:24

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0014_auto_20181109_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsposts',
            name='category',
            field=models.CharField(choices=[('politics', 'POLITICS'), ('entertainment', 'ENTERTAINMENT'), ('sports', 'SPORT')], default='politics', max_length=20),
        ),
        migrations.AlterField(
            model_name='newsposts',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='newsposts',
            name='slug',
            field=models.SlugField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='newsposts',
            name='speaker',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='newsposts',
            name='title',
            field=ckeditor.fields.RichTextField(max_length=1000),
        ),
    ]
