# Generated by Django 2.0.3 on 2018-10-06 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalkZone', '0008_auto_20181005_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talkzone',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
