# Generated by Django 2.0.3 on 2018-10-06 20:35

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TalkZone', '0009_auto_20181006_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talkzone',
            name='body1',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='talkzone',
            name='body2',
            field=ckeditor.fields.RichTextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='talkzone',
            name='description',
            field=ckeditor.fields.RichTextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='talkzone',
            name='subtitle',
            field=ckeditor.fields.RichTextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='talkzone',
            name='title',
            field=ckeditor.fields.RichTextField(max_length=250),
        ),
    ]
