# Generated by Django 2.0.3 on 2018-10-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalkZone', '0011_auto_20181006_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='talkzone',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
