# Generated by Django 2.0.3 on 2018-10-09 11:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TalkZone', '0012_talkzone_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talkzone',
            name='body2',
            field=ckeditor.fields.RichTextField(max_length=2000),
        ),
    ]
