# Generated by Django 2.0.3 on 2018-10-10 08:35

import TalkZone.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalkZone', '0014_auto_20181009_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talkzone',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to=TalkZone.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='talkzone',
            name='middle_image',
            field=models.ImageField(blank=True, upload_to=TalkZone.models.user_directory_path),
        ),
    ]
