# Generated by Django 2.0.3 on 2018-11-11 13:24

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalkZone', '0015_auto_20181010_0935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='talkzone',
            old_name='body1',
            new_name='body',
        ),
        migrations.RemoveField(
            model_name='talkzone',
            name='body2',
        ),
        migrations.RemoveField(
            model_name='talkzone',
            name='middle_image',
        ),
        migrations.AlterField(
            model_name='comments',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='comments',
            name='slug',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='talkzone',
            name='description',
            field=ckeditor.fields.RichTextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='talkzone',
            name='poster',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='talkzone',
            name='slug',
            field=models.SlugField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='talkzone',
            name='subbody',
            field=ckeditor.fields.RichTextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='talkzone',
            name='subtitle',
            field=ckeditor.fields.RichTextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='talkzone',
            name='title',
            field=ckeditor.fields.RichTextField(max_length=1000),
        ),
    ]
