# Generated by Django 2.0.3 on 2018-11-13 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TalkZone', '0016_auto_20181111_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talkzone',
            name='subbody',
        ),
        migrations.RemoveField(
            model_name='talkzone',
            name='subtitle',
        ),
    ]
