# Generated by Django 2.0.3 on 2018-10-11 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0024_comments_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='publish',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mixtape',
            name='publish',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='music',
            name='publish',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='video',
            name='publish',
            field=models.BooleanField(default=True),
        ),
    ]
