# Generated by Django 2.0.3 on 2018-10-12 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0025_auto_20181011_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mixtape',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
