# Generated by Django 2.0.3 on 2018-10-12 07:45

import Music.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0026_auto_20181012_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='audio',
            field=models.FileField(blank=True, upload_to=Music.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='audio',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to=Music.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='audio',
            name='publish',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mixtape',
            name='tape',
            field=models.FileField(blank=True, upload_to=Music.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='mixtape',
            name='tape_image',
            field=models.FileField(blank=True, upload_to=Music.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='music',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to=Music.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(blank=True, upload_to=Music.models.user_directory_path),
        ),
    ]
