# Generated by Django 2.0.3 on 2018-10-12 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0027_auto_20181012_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='publish',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='video',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
