# Generated by Django 2.0.3 on 2018-10-12 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0028_auto_20181012_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to='cover_imgae/'),
        ),
    ]
