# Generated by Django 2.0.3 on 2018-11-09 13:22

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0030_mixtape_dj_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='youtube_link',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='add youtube link here'),
        ),
        migrations.AlterField(
            model_name='music',
            name='about_song',
            field=ckeditor.fields.RichTextField(max_length=1000),
        ),
    ]
