# Generated by Django 2.0.3 on 2018-11-11 13:24

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0031_auto_20181109_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audiocount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Mixtapecount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Videodcount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='audio',
            name='slug',
            field=models.SlugField(max_length=500, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='audio',
            name='slug_title',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='mixtape',
            name='dj_name',
            field=models.CharField(default='Dj Appostle', max_length=200),
        ),
        migrations.AlterField(
            model_name='mixtape',
            name='slug',
            field=models.SlugField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='mixtape',
            name='tape_name',
            field=ckeditor.fields.RichTextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='mixtape',
            name='tracks',
            field=ckeditor.fields.RichTextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='music',
            name='about_song',
            field=ckeditor.fields.RichTextField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='music',
            name='album',
            field=models.CharField(default='No Album', max_length=500),
        ),
        migrations.AlterField(
            model_name='music',
            name='artist',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='music',
            name='featured_artist',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='music',
            name='genre',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='music',
            name='released_Year',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='music',
            name='song_title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='music',
            name='uploader',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='video',
            name='slug',
            field=models.SlugField(max_length=500, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='slug_title',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='videodcount',
            name='number_of_download',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Music.Video'),
        ),
        migrations.AddField(
            model_name='mixtapecount',
            name='number_of_download',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Music.Mixtape'),
        ),
        migrations.AddField(
            model_name='audiocount',
            name='number_of_download',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Music.Audio'),
        ),
    ]
