# Generated by Django 2.0.3 on 2018-11-22 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0034_auto_20181116_1614'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Videodcount',
            new_name='VideoCount',
        ),
    ]
