# Generated by Django 2.0.3 on 2018-12-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0035_auto_20181122_0640'),
    ]

    operations = [
        migrations.CreateModel(
            name='dont_eat_baby_food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Temp', models.CharField(max_length=200)),
            ],
        ),
    ]
