"""
Django settings for NaijaLatest project.

Generated by 'django-admin startproject' using Django 2.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os
from .email_info import *
import dj_database_url
# import django_heroku

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'ngfncjll5%n^%q9t5cf+g9u23n%k&2c+#m79%w*dska+k&_6jo'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['sinzuumyst.net', 'sinzumystery.herokuapp.com', 'sin4.herokuapp.com', '127.0.0.1']

EMAIL_USE_TLS = EMAIL_USE_TLS
EMAIL_HOST = EMAIL_HOST
EMAIL_HOST_USER = EMAIL_HOST_USER
EMAIL_HOST_PASSWORD = EMAIL_HOST_PASSWORD
EMAIL_PORT = EMAIL_PORT


# Application definition

INSTALLED_APPS = [
    'Music.apps.MusicConfig',
    'News.apps.NewsConfig',
    'Gist.apps.GistConfig',
    'Profile.apps.ProfileConfig',
    'Frontend.apps.FrontendConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django_extensions',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'debug_toolbar',

    'social_django',
    'NaijaLatest',
    'TalkZone.apps.TalkzoneConfig',
    'Mysteries.apps.MysteriesConfig',
    'ckeditor',
    'ckeditor_uploader',
    'storages',
    'hitcount',
    # 'ads',



]
CKEDITOR_UPLOAD_PATH = "uploads/"

CKEDITOR_CONFIGS = {
    'default': {
        'height': 300,
        'toolbar': 'default',
        'toolbar_default': [
            ['Styles', 'Format', 'Bold', 'Italic', 'Strike',
             'SpellChecker', 'Undo', 'Redo'],
            ['Link', 'Unlink', 'Anchor'],
            ['Image', 'Flash', 'Table', 'HorizontalRule'],
            ['TextColor', 'BGColor0'],
            ['Smiley', 'specialChar'],
            ['Youtube'],
            ['Source'],
            ['Scayt'],
            ['Embed']
        ],
        'extraPlugins': ','.join(['youtube', 'scayt', 'embed']),


    },
    'special': {
        'toolbar': 'special',
        'height': 100,
        'toolbar_special': [
            ['Styles', 'Format', 'Bold', 'Italic', 'SpellChecker'],
            ['TextColor', 'BGColor'],
            ['SpecialChar'],
            ['Scayt'],
        ],
        'extraPlugins': 'scayt',
    },
    'specialtape':{
        'toolbar': 'specialtape',
        'toolbar_specialtape': [
            ['Image'],
        ],
    }
}


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',

    'social_django.middleware.SocialAuthExceptionMiddleware',
]

ROOT_URLCONF = 'NaijaLatest.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',

                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
                'Music.context_processors.song',
                'Profile.context_processors.profile',
                'TalkZone.context_processors.unpublished',
                'Mysteries.context_processors.unpublished',
                'Frontend.context_processor.times',
                'Frontend.context_processor.talkzone',
            ],
        },
    },
]

AUTHENTICATION_BACKENDS = (
    'social_core.backends.github.GithubOAuth2',
    'social_core.backends.twitter.TwitterOAuth',
    'social_core.backends.facebook.FacebookOAuth2',
    'social_core.backends.open_id.OpenIdAuth',  # for Google authentication
    'social_core.backends.google.GoogleOpenId',  # for Google authentication
    'social_core.backends.google.GoogleOAuth2',  # for Google authentication
    'django.contrib.auth.backends.ModelBackend',

)
SOCIAL_AUTH_URL_NAMESPACE = 'social'
WSGI_APPLICATION = 'NaijaLatest.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases
#
DATABASES = {
     'default': {
             'ENGINE': 'django.db.backends.postgresql_psycopg2',
             'NAME': 'naijalatest',
             'USER': 'postgres',
             'PASSWORD': 'onoyimaobia'
     }
}

# DATABASES = {
#     'default': dj_database_url.config(
#         default='DATABASE_URL'
#     )
# }

SOCIAL_AUTH_POSTGRES_JSONFIELD = True
# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

SHARE_URL = "https://sinzumystery.herokuapp.com/Gist/display_gist"
SHARE_TALKZONE_URL = "https://sinzumystery.herokuapp.com//talk_zone_view.html"
LOGIN_URL = 'profile/login'
LOGOUT_URL = 'logout'
LOGIN_REDIRECT_URL = 'home1'

SOCIAL_AUTH_FACEBOOK_KEY = '276569669840426'  # App ID
SOCIAL_AUTH_FACEBOOK_SECRET = '36ffa2d12d0a1ed1c507b9223f1b4c9d'  # App Secret

SOCIAL_AUTH_GITHUB_KEY = '7d2c254958d044ac8997'
SOCIAL_AUTH_GITHUB_SECRET = '016fd2728b0c76e05b10691d480e9cf6111ac210'

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY ='742838240102-vc2av397nnkc7ope5sofba9eg43mgamm.apps.googleusercontent.com'  #Paste CLient Key
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = 'Ild3hdNdPwVSrfPq_rqsmXrQ' #Paste Secret Key
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

# DEBUG_TOOLBAR_PANELS = [
#     'debug_toolbar.panels.versions.VersionsPanel',
#     'debug_toolbar.panels.timer.TimerPanel',
#     'debug_toolbar.panels.settings.SettingsPanel',
#     'debug_toolbar.panels.headers.HeadersPanel',
#     'debug_toolbar.panels.request.RequestPanel',
#     'debug_toolbar.panels.sql.SQLPanel',
#     'debug_toolbar.panels.staticfiles.StaticFilesPanel',
#     'debug_toolbar.panels.templates.TemplatesPanel',
#     'debug_toolbar.panels.cache.CachePanel',
#     'debug_toolbar.panels.signals.SignalsPanel',
#     'debug_toolbar.panels.logging.LoggingPanel',
#     'debug_toolbar.panels.redirects.RedirectsPanel',
# ]

# STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static/')

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'NaijaLatest/static'),
)


MEDIA_ROOT = os.path.join(BASE_DIR, 'NaijaLatest/media')
MEDIA_URL = '/media/'


SOCIAL_AUTH_REDIRECT_IS_HTTPS = True

CONTENT_TYPES = ['image', 'video']
# 1.25MB = 1310720
# 2.5MB - 2621440
# 5MB - 5242880
# 10MB - 10485760
# 20MB - 20971520
# 50MB - 5242880
# 100MB 104857600
# 250MB - 214958080
# 500MB - 429916160
MAX_UPLOAD_SIZE = "1310720"


# STATIC_URL = '/static/'
# Hit Count setting
HITCOUNT_HITS_PER_IP_LIMIT = 0
HITCOUNT_KEEP_HIT_IN_DATABASE = { 'days': 30 }
# AWS settings

AWS_ACCESS_KEY_ID = 'AKIAI22WFQUAG3BGBJFQ'
AWS_SECRET_ACCESS_KEY = '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'
AWS_STORAGE_BUCKET_NAME = 'sinnzuumystery'
AWS_S3_CUSTOM_DOMAIN = '%s.s3.amazonaws.com' % AWS_STORAGE_BUCKET_NAME
AWS_S3_OBJECT_PARAMETERS = {
    'CacheControl': 'max-age=86400',
}
AWS_LOCATION = 'static'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'NaijaLatest/static'),
    os.path.join(BASE_DIR, 'NaijaLatest/media'),

]

STATIC_URL = 'https://%s/%s/' % (AWS_S3_CUSTOM_DOMAIN, AWS_LOCATION)
STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

DEFAULT_FILE_STORAGE = 'NaijaLatest.storage_backends.MediaStorage'

INTERNAL_IPS = ['sinzumystery.herokuapp.com', '127.0.0.1']
# Activate Django-Heroku.
# django_heroku.settings(locals())


# django ads
# ADS_GOOGLE_ADSENSE_CLIENT = 'ca-pub-xxxxxxxxxxxxxxxx'  # OPTIONAL - DEFAULT TO None

ADS_ZONES = {
    'header': {
        'name': ('Header'),
        'ad_size': {
            'xs': '280x251',
            'sm': '302x251',
            'md': '302x251',
            'lg': '302x251',
            'xl': '302x251'
        },
        #'google_adsense_slot': 'xxxxxxxxx',  # OPTIONAL - DEFAULT TO None
        #'google_adsense_format': 'auto',  # OPTIONAL - DEFAULT TO None
    },
    'content': {
        'name': ('Content'),
        'ad_size': {
            'xs': '280x251',
            'sm': '302x251',
            'md': '302x251',
            'lg': '302x251',
            'xl': '302x251'
        },
        #'google_adsense_slot': 'xxxxxxxxx',  # OPTIONAL - DEFAULT TO None
        #'google_adsense_format': 'auto',  # OPTIONAL - DEFAULT TO None
    },
    'sidebar': {
        'name': ('Sidebar'),
        'ad_size': {
            'xs': '280x251',
            'sm': '302x251',
            'md': '302x251',
            'lg': '302x251',
            'xl': '302x251'
        },
        #'google_adsense_slot': 'xxxxxxxxx',  # OPTIONAL - DEFAULT TO None
        #'google_adsense_format': 'auto',  # OPTIONAL - DEFAULT TO None
    },
}
# ADS_DEFAULT_AD_SIZE = '720x150'
#
# ADS_DEVICES = (
#     ('xs', 'Extra small devices'),
#     ('sm', 'Small devices'),
#     ('md', 'Medium devices (Tablets)'),
#     ('lg', 'Large devices (Desktops)'),
#     ('xl', 'Extra large devices (Large Desktops)'),
# )
#
# ADS_VIEWPORTS = {
#     'xs': 'd-block img-fluid d-sm-none',
#     'sm': 'd-none img-fluid d-sm-block d-md-none',
#     'md': 'd-none img-fluid d-md-block d-lg-none',
#     'lg': 'd-none img-fluid d-lg-block d-xl-none',
#     'xl': 'd-none img-fluid d-xl-block',
# }
